### ISSUE TITLE
King Attack

### ISSUE THREAD

**Issue by rj-pe** [rj-pe/CIS434_Spring2019_G5#9]
- [x] feature/check
- [x] feature/checkmate

**Comment by gskairyu** [comment]
Hey RJ,

I'm getting the following errors when I try to select pieces from the master branch.

Exception in thread "main" java.lang.NullPointerException
	at boardlogic.Player.addToThreatenedSpaces(Player.java:78)
	at CMDChess.main(CMDChess.java:91)

I'm not sure where the logic is going off there, but wanted to see if you might have an idea.

Thanks,

Alex
